### ISSUE TITLE
Сделать обязательной newline at the end of file

### ISSUE THREAD

**Issue by isqua** [htmlacademy/editorconfig-cli#8]
Сейчас это не ошибка, а ворнинг. Поэтому команда `npm test` заканчивается с кодом `0`. И даже если у студента куча файлов где нет `\n` в конце, тревис ему говорит, что всё ок.

<img width="460" alt="npm_test" src="https://cloud.githubusercontent.com/assets/529247/18726195/0150bfc6-804c-11e6-8138-7880715eeddc.png">

**Comment by zeckson** [comment]
Блин, это жесткий косяк =(
