### ISSUE TITLE
Баг или фитча?

### ISSUE THREAD

**Issue by nicothin** [htmlacademy/editorconfig-cli#9]
https://github.com/htmlacademy-adaptive/130134-pink/pull/2/files#diff-bebe1109d1dee7b50aa4046a854a871fR42 - в конфиге прописаны отступы в 2 пробела, но пропускаются и 4

**Comment by meritt** [comment]
@nicothin а лог приложи, где видно, что что-то не так.

**Comment by nicothin** [comment]
@meritt в том и дело, что проверка дает «все отлично», хотя отступ у отмеченной строки не 2, а 4 пробела.

**Comment by meritt** [comment]
@nicothin дк ты можешь этот результат приложить?

**Comment by nicothin** [comment]
https://travis-ci.org/htmlacademy-adaptive/130134-pink/jobs/161751698
едиторконфиг стандартный...

**Comment by meritt** [comment]
@nicothin я вижу, что вы используете `lintspaces`, а репозиторий про `editorconfig-cli`. И ученикам в третьем разделе приехал другой линтер, как раз `editorconfig-cli`. Видимо закрываю ишью?
